name: Terraform GitOps Workflow

on:
  push:
    branches:
      - main     # Triggers the workflow only on the main branch
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform GitOps Automation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.6 # Replace with your Terraform version

      - name: Terraform Init
        working-directory: ./terraform  # Specify the path to your Terraform directory
        run: terraform init

      - name: Terraform Format
        working-directory: ./terraform  # Specify the path to your Terraform directory
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./terraform  # Specify the path to your Terraform directory
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform  # Specify the path to your Terraform directory
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-northeast-1'

      - name: Terraform Apply (Manual Approval Required)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./terraform  # Specify the path to your Terraform directory
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-northeast-1'
