name: Terraform GitOps Workflow

on:
  push:
    branches:
      - main     # Triggers the workflow only on the main branch
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform GitOps Automation
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Allows GitHub to use OIDC tokens
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}   # Use the AWS role you created
          aws-region: ${{ secrets.AWS_REGION }}         # Use your AWS region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.6 # Replace with your Terraform version

      - name: Terraform Init
        working-directory: ./terraform  # Specify the path to your Terraform directory
        run: terraform init

      - name: Terraform Format
        working-directory: ./terraform  # Specify the path to your Terraform directory
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./terraform  # Specify the path to your Terraform directory
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform  # Specify the path to your Terraform directory
        run: terraform plan

      - name: Terraform Apply (Manual Approval Required)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./terraform  # Specify the path to your Terraform directory
        run: terraform apply -auto-approve
